cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'gnupg'
brew 'grc'
brew 'jq'
brew 'libgit2'
brew 'node'
brew 'pinentry-mac'
brew 'readline'
brew 'the_silver_searcher'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'alfred'
cask 'amethyst'
cask 'chromium'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'forklift'
cask 'handbrake'
cask 'iterm2'
cask 'ngrok'
cask 'slack'
cask 'spotify'
cask 'table-tool'
cask 'transmission'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'

mas 'DoubleShot', id: 1076145960
